#Email Settings

EMAIL_USE_TLS = True

EMAIL_HOST = 'smtp.gmail.com'

#Enter your email id
EMAIL_HOST_USER = ''

#Enter the password generated by google security
EMAIL_HOST_PASSWORD = ''

EMAIL_PORT = 587
